name: Release to GitHub

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        run: ./.github/workflows/create-release.sh ${{github.ref_name}}

  linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install gcc-aarch64-linux-gnu
        run: sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Release linux x86_64 gnu
        run: ./.github/workflows/build-release.sh x86_64-unknown-linux-gnu
      - name: Release linux x86_64 musl
        run: ./.github/workflows/build-release.sh x86_64-unknown-linux-musl
      - name: Release linux i686 musl
        run: ./.github/workflows/build-release.sh i686-unknown-linux-musl
      - name: Release linux aarch64 musl
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc
        run: ./.github/workflows/build-release.sh aarch64-unknown-linux-musl

  windows:
    needs: create_release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release windows x86_64
        run: ./.github/workflows/build-release.sh x86_64-pc-windows-msvc
      - name: Release windows i686
        run: ./.github/workflows/build-release.sh i686-pc-windows-msvc

  macos:
    needs: create_release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release macos x86_64
        run: ./.github/workflows/build-release.sh x86_64-apple-darwin
      - name: Release macos aarch64
        run: ./.github/workflows/build-release.sh aarch64-apple-darwin
